[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eval_rebot_arm_dm"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "draccus",
    "matplotlib",
    "ipython",
    "msgpack==1.1.0",
    "msgpack-numpy==0.4.8",
    "zmq",
    "transformers",
    "lerobot @ git+https://github.com/Seeed-Projects/lerobot.git@0f392484458cb5ebca0310c0c4c47390a31c80ed",
    "lerobot-robot-seeed-b601 @ git+https://github.com/Seeed-Projects/lerobot-robot-seeed-b601.git@5d36bef6e352ddfc4cefc40a16db02772e25655c",
    "motorbridge",
]

# Please also manually install `uv pip install --no-deps -e ../../`
